/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "tvugghippwvoxsjqyxkr"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR2dWdnaGlwcHd2b3hzanF5eGtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxNjgwODEsImV4cCI6MjA4NTc0NDA4MX0.KTfejXXgrrdy4gUMekm--v2jtqXO0DARPAjzYmfqv30"